#!/usr/bin/env bash
#Script to print "Bad Luck @4 and Good luck @8 else Best School"
i="1"
while [ $i -lt 11 ]
do
	if [ $i = 4 ]
	then 
		echo "bad luck"
	elif [ $i = 8 ]
	then 
		echo "good luck"
	else 
		echo "Best School"
	fi
	i=$((i+1))
done
