#!/usr/bin/env bash
# Script for priniting number from 1 to 20
i="1"
while [ $i -lt 21 ]
do
	echo $i
	i=$((i+1))
	case $i in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
esac
done
